[wokwi]
version = 1
firmware = ".pio/build/esp32/firmware.bin"
diagram = "diagram.json"
rfc2217ServerPort = 4000

[simulators]
wifi = "enabled"

[[net.forward]]
from = "localhost:8080"
to = "target:8080"
